Repository googleworkspace/browser-samples, pull requests merged in 2022-07, with the labels that each got.

#118 test: unit test case for sheet snippets
  sheets/snippets/test_append_spreadsheet_values.js
  sheets/snippets/test_batch_get_spreadsheet_values.js
  sheets/snippets/test_batch_update_spreadsheet.js
  sheets/snippets/test_batch_update_spreadsheet_values.js
  sheets/snippets/test_conditionally_format.js
  sheets/snippets/test_create_pivot_tables.js
  sheets/snippets/test_create_spreadsheet.js
  sheets/snippets/test_get_spreadsheet_values.js
  sheets/snippets/test_update_spreadsheet_values.js
Labels: javascript

#120 feat: browser samples slides-snippets updated
  slides/snippets/slides_copy_presentation.js
  slides/snippets/slides_create_bulleted_text.js
  slides/snippets/slides_create_image.js
  slides/snippets/slides_create_presentation.js
  slides/snippets/slides_create_sheets_chart.js
  slides/snippets/slides_create_slide.js
  slides/snippets/slides_create_textbox_with_text.js
  slides/snippets/slides_image_merging.js
  slides/snippets/slides_refresh_sheets_chart.js
  slides/snippets/slides_simple_text_replace.js
  slides/snippets/slides_text_merging.js
  slides/snippets/slides_text_style_update.js
Labels: javascript

#125 chore: standardize workflows
  .github/workflows/lint.yaml
  .github/workflows/lint.yml
Labels: yaml

#126 chore: add license headers
  .eslintrc.js
Labels: javascript

#129 chore: switch to main
  README.md
Labels: markdown
